plugins {
    id 'java'
    id 'application'
}

group = 'oo.cc'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'oo.cc.Main'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
    maxHeapSize = "1024m"
}